import express from "express";
import path from "path";
import { fileURLToPath } from "url";
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express();
app.get("/health",(_req,res)=>res.json({ok:true,app:"hermes-one-web"}));
app.use(express.static(path.join(__dirname,"dist")));
app.get("*",(_req,res)=>res.sendFile(path.join(__dirname,"dist","index.html")));
const port=process.env.PORT||10000;
app.listen(port,"0.0.0.0",()=>console.log("HERMES_ONE_WEB_READY port="+port));